version: '3'
services:
  web:
    build: .
    ports:
      - "8888:5000"
    volumes:
      - "/media/cvg_anno/datasets:/usr/storage"
  db:
    image: mongo
    restart: always
    volumes:
      - "/media/cvg_anno/mongodb:/data/db"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongodb
      # MONGO_INITDB_ROOT_PASSWORD: 
