version: '3'
services:
  web:
    build: .
    ports:
      - "8888:5000"
    volumes:
      - "/usr/share/cvg/datasets:/usr/storage"
  db:
    image: mongo:4.2.3
    restart: always
    volumes:
      - "/usr/share/cvg/mongodb:/data/db"
      # environment:
      #   MONGO_INITDB_ROOT_USERNAME: mongodb
      # MONGO_INITDB_ROOT_PASSWORD: